import "./globals.css";

export const metadata = {
  title: "Bed RSUP Makassar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className="antialiased bg-[#121212] text-gray-900"
      >
        <div className="flex h-screen overflow-hidden">
          <div className="flex flex-col flex-1 overflow-auto bg-[#f0f5f5]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}